package com.briup.order.sms.mapper;

import com.briup.order.sms.bean.Cust;
import com.briup.order.sms.bean.CustExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CustMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btsf_cust
     *
     * @mbg.generated Wed May 15 19:04:08 CST 2019
     */
    long countByExample(CustExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btsf_cust
     *
     * @mbg.generated Wed May 15 19:04:08 CST 2019
     */
    int deleteByExample(CustExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btsf_cust
     *
     * @mbg.generated Wed May 15 19:04:08 CST 2019
     */
    int deleteByPrimaryKey(Long custId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btsf_cust
     *
     * @mbg.generated Wed May 15 19:04:08 CST 2019
     */
    int insert(Cust record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btsf_cust
     *
     * @mbg.generated Wed May 15 19:04:08 CST 2019
     */
    int insertSelective(Cust record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btsf_cust
     *
     * @mbg.generated Wed May 15 19:04:08 CST 2019
     */
    List<Cust> selectByExample(CustExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btsf_cust
     *
     * @mbg.generated Wed May 15 19:04:08 CST 2019
     */
    Cust selectByPrimaryKey(Long custId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btsf_cust
     *
     * @mbg.generated Wed May 15 19:04:08 CST 2019
     */
    int updateByExampleSelective(@Param("record") Cust record, @Param("example") CustExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btsf_cust
     *
     * @mbg.generated Wed May 15 19:04:08 CST 2019
     */
    int updateByExample(@Param("record") Cust record, @Param("example") CustExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btsf_cust
     *
     * @mbg.generated Wed May 15 19:04:08 CST 2019
     */
    int updateByPrimaryKeySelective(Cust record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btsf_cust
     *
     * @mbg.generated Wed May 15 19:04:08 CST 2019
     */
    int updateByPrimaryKey(Cust record);
}