package com.briup.order.sms.mapper;

import com.briup.order.sms.bean.Dishes;
import com.briup.order.sms.bean.DishesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DishesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btsf_dishes
     *
     * @mbg.generated Wed May 15 19:04:08 CST 2019
     */
    long countByExample(DishesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btsf_dishes
     *
     * @mbg.generated Wed May 15 19:04:08 CST 2019
     */
    int deleteByExample(DishesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btsf_dishes
     *
     * @mbg.generated Wed May 15 19:04:08 CST 2019
     */
    int deleteByPrimaryKey(Integer dishesId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btsf_dishes
     *
     * @mbg.generated Wed May 15 19:04:08 CST 2019
     */
    int insert(Dishes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btsf_dishes
     *
     * @mbg.generated Wed May 15 19:04:08 CST 2019
     */
    int insertSelective(Dishes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btsf_dishes
     *
     * @mbg.generated Wed May 15 19:04:08 CST 2019
     */
    List<Dishes> selectByExample(DishesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btsf_dishes
     *
     * @mbg.generated Wed May 15 19:04:08 CST 2019
     */
    Dishes selectByPrimaryKey(Integer dishesId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btsf_dishes
     *
     * @mbg.generated Wed May 15 19:04:08 CST 2019
     */
    int updateByExampleSelective(@Param("record") Dishes record, @Param("example") DishesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btsf_dishes
     *
     * @mbg.generated Wed May 15 19:04:08 CST 2019
     */
    int updateByExample(@Param("record") Dishes record, @Param("example") DishesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btsf_dishes
     *
     * @mbg.generated Wed May 15 19:04:08 CST 2019
     */
    int updateByPrimaryKeySelective(Dishes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btsf_dishes
     *
     * @mbg.generated Wed May 15 19:04:08 CST 2019
     */
    int updateByPrimaryKey(Dishes record);
}