package com.briup.order.sms.bean;

public class Classify {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column btsf_classify.classify_id
     *
     * @mbg.generated Wed May 15 19:04:08 CST 2019
     */
    private Integer classifyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column btsf_classify.classify_name
     *
     * @mbg.generated Wed May 15 19:04:08 CST 2019
     */
    private String classifyName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column btsf_classify.classify_id
     *
     * @return the value of btsf_classify.classify_id
     *
     * @mbg.generated Wed May 15 19:04:08 CST 2019
     */
    public Integer getClassifyId() {
        return classifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column btsf_classify.classify_id
     *
     * @param classifyId the value for btsf_classify.classify_id
     *
     * @mbg.generated Wed May 15 19:04:08 CST 2019
     */
    public void setClassifyId(Integer classifyId) {
        this.classifyId = classifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column btsf_classify.classify_name
     *
     * @return the value of btsf_classify.classify_name
     *
     * @mbg.generated Wed May 15 19:04:08 CST 2019
     */
    public String getClassifyName() {
        return classifyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column btsf_classify.classify_name
     *
     * @param classifyName the value for btsf_classify.classify_name
     *
     * @mbg.generated Wed May 15 19:04:08 CST 2019
     */
    public void setClassifyName(String classifyName) {
        this.classifyName = classifyName == null ? null : classifyName.trim();
    }
}