package com.briup.order.sms.bean;

public class Cust {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column btsf_cust.cust_id
     *
     * @mbg.generated Wed May 15 19:04:08 CST 2019
     */
    private Long custId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column btsf_cust.cust_phone
     *
     * @mbg.generated Wed May 15 19:04:08 CST 2019
     */
    private String custPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column btsf_cust.cust_password
     *
     * @mbg.generated Wed May 15 19:04:08 CST 2019
     */
    private String custPassword;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column btsf_cust.cust_id
     *
     * @return the value of btsf_cust.cust_id
     *
     * @mbg.generated Wed May 15 19:04:08 CST 2019
     */
    public Long getCustId() {
        return custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column btsf_cust.cust_id
     *
     * @param custId the value for btsf_cust.cust_id
     *
     * @mbg.generated Wed May 15 19:04:08 CST 2019
     */
    public void setCustId(Long custId) {
        this.custId = custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column btsf_cust.cust_phone
     *
     * @return the value of btsf_cust.cust_phone
     *
     * @mbg.generated Wed May 15 19:04:08 CST 2019
     */
    public String getCustPhone() {
        return custPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column btsf_cust.cust_phone
     *
     * @param custPhone the value for btsf_cust.cust_phone
     *
     * @mbg.generated Wed May 15 19:04:08 CST 2019
     */
    public void setCustPhone(String custPhone) {
        this.custPhone = custPhone == null ? null : custPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column btsf_cust.cust_password
     *
     * @return the value of btsf_cust.cust_password
     *
     * @mbg.generated Wed May 15 19:04:08 CST 2019
     */
    public String getCustPassword() {
        return custPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column btsf_cust.cust_password
     *
     * @param custPassword the value for btsf_cust.cust_password
     *
     * @mbg.generated Wed May 15 19:04:08 CST 2019
     */
    public void setCustPassword(String custPassword) {
        this.custPassword = custPassword == null ? null : custPassword.trim();
    }
}