package com.briup.order.sms.bean;

import java.math.BigDecimal;

public class Dishes {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column btsf_dishes.dishes_id
     *
     * @mbg.generated Wed May 15 19:04:08 CST 2019
     */
    private Integer dishesId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column btsf_dishes.dishes_name
     *
     * @mbg.generated Wed May 15 19:04:08 CST 2019
     */
    private String dishesName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column btsf_dishes.dishes_referral
     *
     * @mbg.generated Wed May 15 19:04:08 CST 2019
     */
    private String dishesReferral;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column btsf_dishes.dishes_price
     *
     * @mbg.generated Wed May 15 19:04:08 CST 2019
     */
    private BigDecimal dishesPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column btsf_dishes.dishes_image
     *
     * @mbg.generated Wed May 15 19:04:08 CST 2019
     */
    private String dishesImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column btsf_dishes.dishes_classify_id
     *
     * @mbg.generated Wed May 15 19:04:08 CST 2019
     */
    private Integer dishesClassifyId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column btsf_dishes.dishes_id
     *
     * @return the value of btsf_dishes.dishes_id
     *
     * @mbg.generated Wed May 15 19:04:08 CST 2019
     */
    public Integer getDishesId() {
        return dishesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column btsf_dishes.dishes_id
     *
     * @param dishesId the value for btsf_dishes.dishes_id
     *
     * @mbg.generated Wed May 15 19:04:08 CST 2019
     */
    public void setDishesId(Integer dishesId) {
        this.dishesId = dishesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column btsf_dishes.dishes_name
     *
     * @return the value of btsf_dishes.dishes_name
     *
     * @mbg.generated Wed May 15 19:04:08 CST 2019
     */
    public String getDishesName() {
        return dishesName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column btsf_dishes.dishes_name
     *
     * @param dishesName the value for btsf_dishes.dishes_name
     *
     * @mbg.generated Wed May 15 19:04:08 CST 2019
     */
    public void setDishesName(String dishesName) {
        this.dishesName = dishesName == null ? null : dishesName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column btsf_dishes.dishes_referral
     *
     * @return the value of btsf_dishes.dishes_referral
     *
     * @mbg.generated Wed May 15 19:04:08 CST 2019
     */
    public String getDishesReferral() {
        return dishesReferral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column btsf_dishes.dishes_referral
     *
     * @param dishesReferral the value for btsf_dishes.dishes_referral
     *
     * @mbg.generated Wed May 15 19:04:08 CST 2019
     */
    public void setDishesReferral(String dishesReferral) {
        this.dishesReferral = dishesReferral == null ? null : dishesReferral.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column btsf_dishes.dishes_price
     *
     * @return the value of btsf_dishes.dishes_price
     *
     * @mbg.generated Wed May 15 19:04:08 CST 2019
     */
    public BigDecimal getDishesPrice() {
        return dishesPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column btsf_dishes.dishes_price
     *
     * @param dishesPrice the value for btsf_dishes.dishes_price
     *
     * @mbg.generated Wed May 15 19:04:08 CST 2019
     */
    public void setDishesPrice(BigDecimal dishesPrice) {
        this.dishesPrice = dishesPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column btsf_dishes.dishes_image
     *
     * @return the value of btsf_dishes.dishes_image
     *
     * @mbg.generated Wed May 15 19:04:08 CST 2019
     */
    public String getDishesImage() {
        return dishesImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column btsf_dishes.dishes_image
     *
     * @param dishesImage the value for btsf_dishes.dishes_image
     *
     * @mbg.generated Wed May 15 19:04:08 CST 2019
     */
    public void setDishesImage(String dishesImage) {
        this.dishesImage = dishesImage == null ? null : dishesImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column btsf_dishes.dishes_classify_id
     *
     * @return the value of btsf_dishes.dishes_classify_id
     *
     * @mbg.generated Wed May 15 19:04:08 CST 2019
     */
    public Integer getDishesClassifyId() {
        return dishesClassifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column btsf_dishes.dishes_classify_id
     *
     * @param dishesClassifyId the value for btsf_dishes.dishes_classify_id
     *
     * @mbg.generated Wed May 15 19:04:08 CST 2019
     */
    public void setDishesClassifyId(Integer dishesClassifyId) {
        this.dishesClassifyId = dishesClassifyId;
    }
}